# Generated by Django 6.0.4 on 2026-04-29 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grao_a_grao', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='receita',
            name='categoria',
            field=models.CharField(choices=[('carne', 'Carne'), ('peixe', 'Peixe'), ('vegetariano', 'Vegetariano'), ('vegan', 'Vegan')], default='carne', max_length=50),
        ),
        migrations.AddField(
            model_name='receita',
            name='tipo_prato',
            field=models.CharField(choices=[('entrada', 'Entrada'), ('prato_principal', 'Prato Principal'), ('sobremesa', 'Sobremesa'), ('lanche', 'Lanche/Pequeno-almoço')], default='prato_principal', max_length=50),
        ),
    ]
