# Generated by Django 6.0.4 on 2026-04-30 09:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grao_a_grao', '0002_receita_categoria_receita_tipo_prato'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Planeamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('tipo_refeicao', models.CharField(choices=[('PA', 'Pequeno-almoço'), ('AL', 'Almoço'), ('LA', 'Lanche'), ('JA', 'Jantar')], max_length=2)),
                ('receita', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grao_a_grao.receita')),
                ('utilizador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['data', 'tipo_refeicao'],
            },
        ),
    ]
