# Generated by Django 6.0.4 on 2026-04-30 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grao_a_grao', '0003_planeamento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receita',
            name='tipo_prato',
            field=models.CharField(choices=[('entrada', 'Entrada'), ('principal', 'Prato Principal'), ('sobremesa', 'Sobremesa'), ('lanche_pq_almoco', 'Lanche / Pequeno-Almoço')], default='principal', max_length=50),
        ),
    ]
