# Generated by Django 6.0.4 on 2026-04-30 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grao_a_grao', '0004_alter_receita_tipo_prato'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingrediente',
            name='unidade',
            field=models.CharField(choices=[('gr', 'g'), ('kg', 'kg'), ('uni', 'un'), ('l', 'l'), ('ml', 'ml')], default='gr', max_length=50),
        ),
    ]
