# Generated by Django 6.0.4 on 2026-04-30 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grao_a_grao', '0005_alter_ingrediente_unidade'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingrediente',
            name='secao',
            field=models.CharField(choices=[('legumes_fruta', 'Legumes e Fruta'), ('talho_peixaria', 'Talho e Peixaria'), ('mercearia', 'Mercearia'), ('laticinios_ovos', 'Laticínios e Ovos'), ('congelados', 'Congelados'), ('temperos_especiarias', 'Temperos e Especiarias'), ('outros', 'Outros')], default='outros', max_length=50),
        ),
    ]
