# Generated by Django 6.0.4 on 2026-04-30 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grao_a_grao', '0006_ingrediente_secao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planeamento',
            name='tipo_refeicao',
            field=models.CharField(choices=[('1_pequeno_almoco', 'Pequeno-almoço'), ('2_almoco', 'Almoço'), ('3_lanche', 'Lanche'), ('4_jantar', 'Jantar')], max_length=20),
        ),
    ]
