# Generated by Django 6.0.4 on 2026-04-30 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grao_a_grao', '0007_alter_planeamento_tipo_refeicao'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='planeamento',
            options={'ordering': ['data', 'tipo_refeicao', 'receita__tipo_prato']},
        ),
        migrations.AlterField(
            model_name='receita',
            name='tipo_prato',
            field=models.CharField(choices=[('1_entrada', 'Entrada'), ('2_principal', 'Prato Principal'), ('3_sobremesa', 'Sobremesa'), ('4_lanche_pq_almoco', 'Lanche / Pequeno-Almoço')], default='2_principal', max_length=50),
        ),
    ]
