# Generated by Django 6.0.4 on 2026-05-04 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grao_a_grao', '0008_fix_ordem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receita',
            name='tipo_prato',
            field=models.CharField(choices=[('1_entrada', 'Entrada'), ('1.5_sopa', 'Sopa'), ('2_principal', 'Prato Principal'), ('3_sobremesa', 'Sobremesa'), ('4_lanche_pq_almoco', 'Lanche / Pequeno-Almoço')], default='2_principal', max_length=20),
        ),
    ]
