# Generated by Django 6.0.4 on 2026-05-04 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grao_a_grao', '0009_alter_receita_tipo_prato'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingrediente',
            name='unidade',
            field=models.CharField(choices=[('gr', 'g'), ('kg', 'kg'), ('uni', 'un'), ('l', 'l'), ('ml', 'ml'), ('colher_sopa', 'Colher de Sopa'), ('colher_sobremesa', 'Colher de Sobremesa'), ('chavena', 'Chávena'), ('pitada', 'Pitada')], max_length=20),
        ),
    ]
