# Generated by Django 6.0.4 on 2026-05-04 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grao_a_grao', '0010_alter_ingrediente_unidade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receita',
            name='categoria',
            field=models.CharField(choices=[('carne', 'Carne'), ('peixe', 'Peixe'), ('vegetariano', 'Vegetariano'), ('vegan', 'Vegan'), ('outros', '🍽️ Outros/Geral')], default='carne', max_length=50),
        ),
    ]
