# Generated by Django 6.0.4 on 2026-05-05 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grao_a_grao', '0011_alter_receita_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingrediente',
            name='unidade',
            field=models.CharField(choices=[('gr', 'g'), ('kg', 'kg'), ('uni', 'un'), ('l', 'l'), ('ml', 'ml')], max_length=20),
        ),
        migrations.AlterField(
            model_name='receita',
            name='categoria',
            field=models.CharField(choices=[('carne', '🥩 Carne'), ('peixe', '🐟 Peixe'), ('vegetariano', '🥗 Vegetariano'), ('vegan', '🌱 Vegan'), ('outros', '🍽️ Outros/Geral')], default='carne', max_length=50),
        ),
        migrations.AlterField(
            model_name='receita',
            name='tipo_prato',
            field=models.CharField(choices=[('1_entrada', '🥟 Entrada'), ('1.5_sopa', '🥣 Sopa'), ('2_principal', '🍽️ Prato Principal'), ('3_sobremesa', '🍰 Sobremesa'), ('4_lanche_pq_almoco', '☕🥪 Lanche / Pequeno-Almoço')], default='2_principal', max_length=20),
        ),
    ]
