# Generated by Django 6.0.4 on 2026-05-05 11:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grao_a_grao', '0013_rename_dispensa_to_despensa'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EstadoLista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gerada', models.BooleanField(default=False)),
                ('utilizador', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='estado_lista', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
