# Generated by Django 6.0.4 on 2026-05-05 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grao_a_grao', '0014_estadolista'),
    ]

    operations = [
        migrations.AddField(
            model_name='receita',
            name='is_public',
            field=models.BooleanField(default=False),
        ),
    ]
